"""add resume channel

Revision ID: 56d7d540892d
Revises: 539394634ce1
Create Date: 2026-07-18 11:19:41.495220
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d7d540892d'
down_revision: Union[str, None] = '539394634ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('channel', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_resume_channel'), 'resume', ['channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_channel'), table_name='resume')
    op.drop_column('resume', 'channel')
    # ### end Alembic commands ###
