param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectPath
)


Write-Host "================================="
Write-Host "Build Claude Context"
Write-Host "================================="


$ClaudeFile = Join-Path $ProjectPath "CLAUDE.md"


# 清空旧文件

if(Test-Path $ClaudeFile)
{
    Remove-Item $ClaudeFile -Force
}


"# Claude Project Context" | 
Out-File $ClaudeFile -Encoding utf8


Add-Content $ClaudeFile "" -Encoding utf8


Add-Content $ClaudeFile "# Project Information" -Encoding utf8

Add-Content $ClaudeFile "" -Encoding utf8

Add-Content $ClaudeFile "Generated by OPC AI Software Factory." -Encoding utf8


Add-Content $ClaudeFile "" -Encoding utf8



# ==============================
# Enterprise Context
# ==============================

Add-Content $ClaudeFile "## Enterprise Rules" -Encoding utf8


$enterprise = Join-Path `
$ProjectPath ".factory\claude\enterprise.md"


if(Test-Path $enterprise)
{
    Get-Content $enterprise -Encoding utf8 |
    Add-Content $ClaudeFile -Encoding utf8
}


Add-Content $ClaudeFile "" -Encoding utf8



# ==============================
# Project Context
# ==============================

Add-Content $ClaudeFile "## Project Rules" -Encoding utf8


$project = Join-Path `
$ProjectPath ".factory\claude\project.md"


if(Test-Path $project)
{
    Get-Content $project -Encoding utf8 |
    Add-Content $ClaudeFile -Encoding utf8
}


Add-Content $ClaudeFile "" -Encoding utf8



# ==============================
# Agent Context
# ==============================

Add-Content $ClaudeFile "## Agent Collaboration" -Encoding utf8


$agentsPath = Join-Path $ProjectPath "agents"


if(Test-Path $agentsPath)
{

    Get-ChildItem $agentsPath "*.md" |
    Sort-Object Name |
    ForEach-Object {

        Add-Content $ClaudeFile "" -Encoding utf8

        Add-Content $ClaudeFile "### $($_.BaseName)" -Encoding utf8

        Get-Content $_.FullName -Encoding utf8 |
        Add-Content $ClaudeFile -Encoding utf8

    }

}



Write-Host ""
Write-Host "Claude Context Generated:"
Write-Host $ClaudeFile