param(

    # 项目名称
    [Parameter(Mandatory=$true)]
    [string]$ProjectName,


    # 项目描述
    [Parameter(Mandatory=$false)]
    [string]$Description="OPC AI Generated Project",


    # 项目生成目录
    [Parameter(Mandatory=$false)]
    [string]$TargetPath="./projects"
)



# =================================
# OPC AI Software Factory
# Project Bootstrap
# =================================

Write-Host "================================="
Write-Host "OPC AI Software Factory"
Write-Host "Project Bootstrap"
Write-Host "================================="



# =================================
# Factory路径自动定位
# =================================

$FactoryPath = Split-Path `
$PSScriptRoot `
-Parent


Write-Host ""
Write-Host "Factory Path:"
Write-Host $FactoryPath



# =================================
# 创建项目路径
# =================================

$ProjectPath = Join-Path `
$TargetPath `
$ProjectName



if(Test-Path $ProjectPath)
{
    Write-Host ""
    Write-Host "项目已经存在:"
    Write-Host $ProjectPath

    exit 1
}



New-Item `
-ItemType Directory `
-Path $ProjectPath `
-Force | Out-Null



Write-Host ""
Write-Host "Create Project:"
Write-Host $ProjectPath



# =================================
# 创建基础目录
# =================================

$Folders = @(

    "docs/product",

    "docs/architecture",

    "docs/test",

    "docs/release",

    ".github/ISSUE_TEMPLATE",

    "scripts"

)



foreach($folder in $Folders)
{

    New-Item `
    -ItemType Directory `
    -Path (Join-Path $ProjectPath $folder) `
    -Force | Out-Null

}



Write-Host ""
Write-Host "Base structure created"



# =================================
# Factory模板复制函数
# =================================

function Copy-FactoryTemplate
{

    param(

        [string]$Source,

        [string]$Target

    )


    if(Test-Path $Source)
    {

        Copy-Item `
        -Path $Source `
        -Destination $Target `
        -Recurse `
        -Force


        Write-Host ""
        Write-Host "Template injected:"
        Write-Host $Source

    }
    else
    {

        Write-Host ""
        Write-Host "Template not found:"
        Write-Host $Source

        exit 1

    }

}



# =================================
# 注入Factory Runtime模板
#
# templates/factory
#
#        |
#        ↓
#
# project/.factory
#
# =================================

$FactoryTemplatePath = Join-Path `
$FactoryPath `
"templates/factory"



$ProjectFactoryPath = Join-Path `
$ProjectPath `
".factory"



Copy-FactoryTemplate `
$FactoryTemplatePath `
$ProjectFactoryPath



Write-Host ""
Write-Host "Factory Runtime injected"



# =================================
# 注入GitHub模板
# =================================

$GithubTemplatePath = Join-Path `
$FactoryPath `
"templates/github"



$ProjectGithubPath = Join-Path `
$ProjectPath `
".github"



Copy-FactoryTemplate `
$GithubTemplatePath `
$ProjectGithubPath



Write-Host ""
Write-Host "Github template injected"



# =================================
# 创建README
# =================================

$ReadmeContent = @"

# $ProjectName


$Description


Generated by OPC AI Software Factory.


"@



Set-Content `
-Path (Join-Path $ProjectPath "README.md") `
-Value $ReadmeContent `
-Encoding utf8



Write-Host ""
Write-Host "README generated"



# =================================
# 生成Claude Runtime Context
#
# 唯一CLAUDE.md来源
#
# =================================

Write-Host ""
Write-Host "Building Claude Runtime Context..."



& "$PSScriptRoot\build-claude-context.ps1" `
-ProjectPath $ProjectPath



if($LASTEXITCODE -ne 0)
{

    Write-Host ""
    Write-Host "Claude Context build failed"

    exit 1

}



# =================================
# 初始化Git
# =================================

Set-Location $ProjectPath



git init


git add .


git commit `
-m "chore: initialize project by opc ai factory"



Write-Host ""
Write-Host "Git initialized"



# =================================
# 完成
# =================================

Write-Host ""
Write-Host "================================="
Write-Host "Project Bootstrap Completed"
Write-Host $ProjectPath
Write-Host "================================="