param(

    [Parameter(Mandatory=$true)]
    [string]$ProjectName,

    [Parameter(Mandatory=$false)]
    [string]$Description="OPC AI Generated Project",

    [Parameter(Mandatory=$false)]
    [string]$TargetPath="./projects",

    [Parameter(Mandatory=$false)]
    [string]$FactoryPath="../"
)

# 增加模板复制函数
function Copy-FactoryTemplate
{
    param(
        [string]$Source,
        [string]$Target
    )


    if(Test-Path $Source)
    {
        Copy-Item `
        -Path $Source `
        -Destination $Target `
        -Recurse `
        -Force

        Write-Host "Injected:"
        Write-Host $Source
    }
}

Write-Host "================================="
Write-Host "OPC AI Software Factory"
Write-Host "Project Bootstrap"
Write-Host "================================="


# 创建项目目录

$ProjectPath = Join-Path $TargetPath $ProjectName


if(Test-Path $ProjectPath)
{
    Write-Host "Project already exists:"
    Write-Host $ProjectPath
    exit 1
}


New-Item -ItemType Directory -Path $ProjectPath | Out-Null


Write-Host "Create project:"
Write-Host $ProjectPath



# 基础目录

$folders=@(
    "docs/product",
    "docs/architecture",
    "docs/test",
    "docs/release",
    "agents",
    "scripts",
    ".github/ISSUE_TEMPLATE"
)


foreach($folder in $folders)
{
    New-Item `
    -ItemType Directory `
    -Path (Join-Path $ProjectPath $folder) `
    -Force | Out-Null
}

# 注入 Agent
Copy-Item `
-Path (Join-Path $FactoryPath "templates/agents/*") `
-Destination (Join-Path $ProjectPath "agents") `
-Recurse `
-Force

Write-Host "Injected agents template"

# 注入 GitHub模板
Copy-Item `
-Path (Join-Path $FactoryPath "templates/github/*") `
-Destination (Join-Path $ProjectPath ".github") `
-Recurse `
-Force

Write-Host "Injected github template"

# 注入Claude模板
Copy-Item `
-Path (Join-Path $FactoryPath "templates/claude/*") `
-Destination $ProjectPath `
-Recurse `
-Force

Write-Host "Injected claude template"


# README

@"
# $ProjectName


$Description


Generated by OPC AI Software Factory.

"@ | Out-File `
(Join-Path $ProjectPath "README.md") `
-Encoding utf8



# CLAUDE.md

@"
# $ProjectName

This project is generated by OPC AI Software Factory.

Please read:

- Product requirements
- Architecture documents
- Agent definitions

before development.

"@ | Out-File `
(Join-Path $ProjectPath "CLAUDE.md") `
-Encoding utf8



# Git初始化

Set-Location $ProjectPath


git init


git add .


git commit `
-m "chore: initialize project by opc ai factory"



Write-Host ""
Write-Host "================================="
Write-Host "Project Bootstrap Completed"
Write-Host $ProjectPath
Write-Host "================================="